const CATEGORIES=["Top","Bottom","Dress","Shoes","Jacket","Accessory","Bag","Hair item"];
const WARMTH=["Hot weather","Mild weather","Cool weather","Cold weather","Layer only"];
const COMFORT=["Super comfy","Normal","A little uncomfortable","Itchy/annoying","Short wear only"];
const DAY_TYPES=["School","Orchestra","PE","Weekend","Picture Day","Family Dinner","Field Trip"];
const VIBES=["Cozy","Sporty","Artsy","Classic","Polished","Playful","Simple","Bold","Soft","Preppy","Elegant","Low-effort"];
const ATTN=["Blends in","Cute but safe","A little noticeable","Bold","Special occasion"];
const seedItems=[
["Cream sweater","Top","Sweater","Cream","Solid","Cool weather","Super comfy",["School","Orchestra"],["Cozy","Classic","Soft"],"Cute but safe"],
["Black leggings","Bottom","Leggings","Black","Solid","Cool weather","Super comfy",["School","PE"],["Simple","Sporty"],"Blends in"],
["Sage cardigan","Jacket","Cardigan","Sage","Solid","Layer only","Normal",["School","Orchestra"],["Artsy","Soft"],"Cute but safe"],
["White sneakers","Shoes","Sneakers","White","Solid","Mild weather","Super comfy",["School","PE","Weekend"],["Sporty","Simple"],"Blends in"],
["Floral skirt","Bottom","Skirt","Rose","Floral","Mild weather","Normal",["Weekend","Family Dinner"],["Playful","Artsy"],"A little noticeable"],
["Denim jacket","Jacket","Jacket","Navy","Solid","Layer only","Normal",["School","Weekend"],["Classic","Low-effort"],"Cute but safe"],
["Navy sweatshirt","Top","Sweatshirt","Navy","Solid","Cool weather","Super comfy",["School","Weekend"],["Cozy","Low-effort"],"Blends in"],
["Black boots","Shoes","Boots","Black","Solid","Cold weather","Normal",["School","Family Dinner"],["Polished","Classic"],"A little noticeable"],
["White tee","Top","Tee","White","Solid","Mild weather","Super comfy",["School","Weekend"],["Simple"],"Blends in"],
["Silver bracelet","Accessory","Jewelry","Silver","Solid","Mild weather","Normal",["School","Party"],["Polished"],"Cute but safe"],
["Hair clip","Hair item","Clip","Rose","Solid","Mild weather","Super comfy",["School","Picture Day"],["Playful","Soft"],"Cute but safe"],
["Wide-leg jeans","Bottom","Jeans","Navy","Solid","Cool weather","Normal",["School","Weekend"],["Classic"],"Cute but safe"],
["Rain jacket","Jacket","Rain jacket","Sage","Solid","Layer only","Normal",["School","Field Trip","Travel"],["Sporty"],"Blends in"],
].map((x,i)=>({id:`item-${i+1}`,name:x[0],category:x[1],subcategory:x[2],colorFamily:x[3],pattern:x[4],warmth:x[5],comfort:x[6],bestFor:x[7],vibes:x[8],attentionLevel:x[9]}));
const weather={temperature:52,summary:"Cool morning, warmer afternoon",recommendation:"Light layer recommended",condition:"cool"};
const emptyPref={favoriteVibes:["Cozy","Soft","Classic","Artsy"],favoriteColors:["Cream","Navy","Sage","Black"],avoidedItems:[],outfitPatterns:["You like one delight detail.","You often choose comfortable shoes.","You prefer school-safe outfits with a little personality."],feedbackHistory:[]};
const store={get:(k,d)=>JSON.parse(localStorage.getItem(k)||JSON.stringify(d)),set:(k,v)=>localStorage.setItem(k,JSON.stringify(v))};
const getClosetItems=()=>store.get("closet",seedItems),saveClosetItems=v=>store.set("closet",v); const getSavedOutfits=()=>store.get("outfits",[]),saveSavedOutfits=v=>store.set("outfits",v); const getPreferenceMemory=()=>store.get("prefs",emptyPref),savePreferenceMemory=v=>store.set("prefs",v);
if(!localStorage.getItem("closet")) saveClosetItems(seedItems); if(!localStorage.getItem("prefs")) savePreferenceMemory(emptyPref);
const state={tab:"today",dayType:"School",mood:"Cozy",constraints:[],generated:[],selectedItem:null};
const q=(arr)=>arr[Math.floor(Math.random()*arr.length)];
const scoreItemForContext=(it,c)=>{let s=0;if(it.bestFor.includes(c.dayType))s+=3;if(it.vibes.includes(c.mood))s+=2;if(c.constraints.includes("No jeans today")&&it.subcategory.includes("Jeans"))s-=10;if(c.constraints.includes("Needs sneakers")&&it.category==="Shoes"&&it.subcategory!=="Sneakers")s-=5;if(c.constraints.includes("Rain-ready")&&it.name.toLowerCase().includes("rain"))s+=4;if(c.weather.condition==="cool"&&["Cool weather","Layer only","Cold weather"].includes(it.warmth))s+=2;if(it.lastWorn&&((Date.now()-new Date(it.lastWorn))/86400000)<2)s-=4;if(it.isPaused)s=-99;return s};
const best=(items,c,n=1)=>items.sort((a,b)=>scoreItemForContext(b,c)-scoreItemForContext(a,c)).slice(0,n);
const selectTopAndBottom=(items,c)=>[best(items.filter(i=>i.category==="Top"),c)[0],best(items.filter(i=>i.category==="Bottom"),c)[0]].filter(Boolean);
const selectDressOutfit=(items,c)=>best(items.filter(i=>i.category==="Dress"),c)[0];
const selectShoes=(items,c)=>best(items.filter(i=>i.category==="Shoes"),c)[0];
const selectLayer=(items,c)=>c.weather.condition==="cool"||c.constraints.includes("Warm layers")||c.dayType==="Orchestra"?best(items.filter(i=>i.category==="Jacket"),c)[0]:null;
const selectAccessory=(items,c)=>best(items.filter(i=>["Accessory","Hair item"].includes(i.category)),c)[0];
const createOutfitName=(i)=>q(["Cozy Conservatory","Green Room Energy","Quietly Cool","Soft Athlete","Saturday Artist","Orchestra Ready"])+` ${i+1}`;
const createOutfitExplanation=(ctx,items)=>`Soft, comfortable, and easy for ${ctx.dayType.toLowerCase()}. ${items.some(i=>i.category==='Jacket')?'Your layer supports the cool morning. ':''}Adds one small delight detail without overthinking the morning.`;
function generateOutfits({closetItems,dayType,mood,constraints,weatherContext,preferenceMemory}){const c={dayType,mood,constraints,weather:weatherContext,preferenceMemory}; const active=closetItems.filter(i=>!i.isPaused); return [0,1,2].map(i=>{let main=selectDressOutfit(active,c)?[selectDressOutfit(active,c)]:selectTopAndBottom(active,c); let shoes=selectShoes(active,c),layer=selectLayer(active,c),acc=selectAccessory(active,c); const itemIds=[...main,shoes,layer,acc].filter(Boolean).map(x=>x.id); return {id:`outfit-${Date.now()}-${i}`,name:createOutfitName(i),itemIds,moodTags:[mood],dayTypes:[dayType],weatherFit:weatherContext.condition,explanation:createOutfitExplanation(c,[...main,shoes,layer,acc].filter(Boolean)),comfortScore:4+i%2,weatherScore:4,activityScore:dayType==="PE"?5:4,delightScore:3+i%3,createdAt:new Date().toISOString()};});}
function render(){const app=document.getElementById('app');const items=getClosetItems(),outfits=getSavedOutfits(),prefs=getPreferenceMemory(); const lookup=id=>items.find(i=>i.id===id);
const tabs={today:today(),closet:closet(),outfits:outfitsView(),profile:profile(),item:itemDetail(),add:addItem()};
app.innerHTML=`<div class='app'>${tabs[state.tab]||tabs.today}</div><nav class='bottom-nav'><div class='wrap'>${['today','closet','outfits','profile'].map(t=>`<button class='nav-btn ${state.tab===t?'active':''}' data-nav='${t}'>${t[0].toUpperCase()+t.slice(1)}</button>`).join('')}</div></nav><div id='modal' class='hidden'></div>`;
app.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.nav;render()});
app.querySelectorAll('[data-chip]').forEach(b=>b.onclick=()=>{const {kind,val,multi}=b.dataset; if(multi==='1'){state[kind]=state[kind].includes(val)?state[kind].filter(x=>x!==val):[...state[kind],val]} else state[kind]=val;render()});
app.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>actions[b.dataset.action](b.dataset.id));
function today(){return `<h2>Good morning</h2><p class='muted'>What kind of outfit do you need today?</p><div class='card weather'><h3>${weather.temperature}°F</h3><p>${weather.summary}</p><p>${weather.recommendation}</p></div>${chips('What kind of day is it?','dayType',DAY_TYPES,false)}${chips('How do you want to feel?','mood',["Cozy","Confident","Sporty","Artsy","Polished","Playful","Low-effort","Bold but safe"],false)}${chips('Any constraints?','constraints',["Needs sneakers","No jeans today","Rain-ready","Warm layers","Easy for violin","I only have 5 minutes"],true)}<button class='btn primary' data-action='generate'>Generate outfits</button><button class='btn secondary' data-action='surprise'>Surprise me</button>${state.generated.length?results(state.generated):''}`}
function results(gs){return `<div class='card'><h3>Three looks for today</h3><p class='muted'>${weather.condition} weather · ${state.dayType} · ${state.mood}</p></div>${gs.map(o=>`<div class='card'><h3>${o.name}</h3><div class='grid'>${o.itemIds.map(id=>`<div class='item-photo'>${lookup(id)?.name||''}</div>`).join('')}</div><p>${o.explanation}</p><p>Comfort ${o.comfortScore}/5 · Weather ${o.weatherScore}/5 · Activity ${o.activityScore}/5 · Delight ${o.delightScore}/5</p><button class='btn small' data-action='wear' data-id='${o.id}'>Wear this</button><button class='btn small' data-action='warmer' data-id='${o.id}'>Make warmer</button><button class='btn small' data-action='lessFancy' data-id='${o.id}'>Less fancy</button><button class='btn small' data-action='moreFun' data-id='${o.id}'>More fun</button><button class='btn small' data-action='retry' data-id='${o.id}'>Try again</button></div>`).join('')}`}
function closet(){const f=(document.getElementById('search')?.value||'').toLowerCase();const fs=items.filter(i=>(i.name+i.vibes.join(' ')+i.bestFor.join(' ')).toLowerCase().includes(f));return `<h2>My Closet</h2><input id='search' placeholder='Search closet'/><div class='grid'>${fs.map(i=>`<div class='card' data-action='openItem' data-id='${i.id}'><div class='item-photo'>${i.imageUrl?'<img src="'+i.imageUrl+'"/>' :'Clothing photo'}</div><b>${i.name}</b><p>${i.category}</p><div class='tags'><span class='tag'>${i.vibes[0]||''}</span><span class='tag'>${i.bestFor[0]||''}</span><span class='tag'>${i.warmth}</span></div></div>`).join('')}</div><button class='btn primary' data-action='gotoAdd'>Add item</button>`}
function itemDetail(){const i=items.find(x=>x.id===state.selectedItem);if(!i) return '' ;return `<h2>${i.name}</h2><div class='card'><div class='item-photo'>Photo</div><p>Category: ${i.category}</p><p>Warmth: ${i.warmth}</p><p>Comfort: ${i.comfort}</p><p>Best for: ${i.bestFor.join(', ')}</p><p>Vibe: ${i.vibes.join(', ')}</p><p>Attention: ${i.attentionLevel}</p><p>Last worn: ${i.lastWorn?new Date(i.lastWorn).toDateString():'Not yet'}</p><button class='btn secondary' data-action='markWorn' data-id='${i.id}'>Mark as worn</button><button class='btn secondary' data-action='pause' data-id='${i.id}'>Don’t suggest this for now</button></div>`}
function addItem(){return `<h2>Add something to your closet</h2><div class='card'><input type='file' id='photo'/><input id='name' placeholder='Item name'/><select id='cat'>${CATEGORIES.map(x=>`<option>${x}</option>`)}</select><input id='sub' placeholder='Subcategory'/><input id='color' placeholder='Color family'/><input id='pattern' placeholder='Pattern'/><select id='warm'>${WARMTH.map(x=>`<option>${x}</option>`)}</select><select id='comfort'>${COMFORT.map(x=>`<option>${x}</option>`)}</select><input id='best' placeholder='Best for (comma list)'/><input id='vibes' placeholder='Style vibe (comma list)'/><select id='att'>${ATTN.map(x=>`<option>${x}</option>`)}</select><button class='btn primary' data-action='saveItem'>Save item</button><button class='btn secondary' data-action='saveAdd'>Add another</button></div>`}
function outfitsView(){return `<h2>Favorite Looks</h2>${outfits.length?outfits.map(o=>`<div class='card'><h3>${o.name}</h3><div class='tags'>${o.moodTags.map(t=>`<span class='tag'>${t}</span>`).join('')}</div><p>Last worn: ${o.lastWorn?new Date(o.lastWorn).toDateString():'Not yet'}</p><button class='btn secondary' data-action='wearAgain' data-id='${o.id}'>Wear again</button></div>`).join(''):'<div class="card">No saved outfits yet.</div>'}<button class='btn primary'>Create outfit manually</button>`}
function profile(){return `<h2>Your Style Memory</h2><div class='card'><p>Your style seems to be cozy, classic, and a little artsy.</p></div><div class='card'><h3>Favorite vibes</h3><p>${prefs.favoriteVibes.join(', ')}</p><h3>Colors you pick often</h3><p>${prefs.favoriteColors.join(', ')}</p><h3>Outfit patterns</h3>${prefs.outfitPatterns.map(p=>`<p>• ${p}</p>`).join('')}<h3>Privacy note</h3><p>Morning Muse stores your closet and preferences privately for this prototype. It is here to help you choose, not judge.</p><button class='btn secondary' data-action='resetPrefs'>Reset preferences</button></div>`}
function chips(title,kind,arr,multi){return `<div class='card'><h3>${title}</h3><div class='chips'>${arr.map(v=>`<button class='chip ${multi?state[kind].includes(v):state[kind]===v?'active':''}' data-chip data-kind='${kind}' data-val='${v}' data-multi='${multi?1:0}'>${v}</button>`).join('')}</div></div>`}
const actions={generate(){state.generated=generateOutfits({closetItems:items,dayType:state.dayType,mood:state.mood,constraints:state.constraints,weatherContext:weather,preferenceMemory:prefs});render()},surprise(){state.dayType=q(DAY_TYPES);state.mood=q(["Cozy","Confident","Sporty","Artsy"]);state.constraints=[q(["Needs sneakers","Rain-ready","Warm layers","Easy for violin"])];actions.generate()},openItem(id){state.selectedItem=id;state.tab='item';render()},gotoAdd(){state.tab='add';render()},saveItem(){saveNew(true)},saveAdd(){saveNew(false)},markWorn(id){const u=items.map(i=>i.id===id?{...i,lastWorn:new Date().toISOString()}:i);saveClosetItems(u);render()},pause(id){const u=items.map(i=>i.id===id?{...i,isPaused:true}:i);saveClosetItems(u);render()},wear(id){const o=state.generated.find(x=>x.id===id);openFeedback(o)},retry(){actions.generate()},warmer(){state.constraints=[...new Set([...state.constraints,'Warm layers'])];actions.generate()},lessFancy(){state.mood='Low-effort';actions.generate()},moreFun(){state.mood='Playful';actions.generate()},wearAgain(id){const u=outfits.map(o=>o.id===id?{...o,lastWorn:new Date().toISOString()}:o);saveSavedOutfits(u);render()},resetPrefs(){savePreferenceMemory(emptyPref);render()}};
function saveNew(back){const file=document.getElementById('photo')?.files?.[0];const fr=()=>{const ni={id:`item-${Date.now()}`,name:val('name'),category:val('cat'),subcategory:val('sub'),colorFamily:val('color'),pattern:val('pattern'),warmth:val('warm'),comfort:val('comfort'),bestFor:val('best').split(',').map(s=>s.trim()).filter(Boolean),vibes:val('vibes').split(',').map(s=>s.trim()).filter(Boolean),attentionLevel:val('att'),imageUrl:typeof fileData==='string'?fileData:null}; saveClosetItems([...items,ni]); state.tab= back?'closet':'add'; render();}; const val=id=>document.getElementById(id)?.value||''; let fileData=null; if(file){const r=new FileReader();r.onload=()=>{fileData=r.result;fr()};r.readAsDataURL(file)} else fr();}
function openFeedback(o){const m=document.getElementById('modal');m.className='modal-backdrop';m.innerHTML=`<div class='modal'><h3>Nice choice.</h3><p>How did this outfit feel today?</p>${["Loved it","Pretty good","Too cold","Too warm","Too fancy","Too boring","Uncomfortable","Would wear again"].map(x=>`<button class='btn small fb' data-v='${x}'>${x}</button>`).join('')}<textarea id='note' placeholder='Anything to remember?'></textarea><button class='btn primary' id='saveFb'>Save feedback</button></div>`; let pick='Pretty good'; m.querySelectorAll('.fb').forEach(b=>b.onclick=()=>pick=b.dataset.v); m.querySelector('#saveFb').onclick=()=>{const note=m.querySelector('#note').value; o.feedback={feeling:pick,note,date:new Date().toISOString()}; const p=getPreferenceMemory(); p.feedbackHistory.push(o.feedback); savePreferenceMemory(p); const updatedItems=getClosetItems().map(i=>o.itemIds.includes(i.id)?{...i,lastWorn:new Date().toISOString()}:i); saveClosetItems(updatedItems); if(["Loved it","Would wear again","Pretty good"].includes(pick)) saveSavedOutfits([o,...getSavedOutfits()]); m.className='hidden'; render();}; m.onclick=e=>{if(e.target===m)m.className='hidden'};}
}
render();
